### ISSUE TITLE
Can it be used to dedup media files?

### ISSUE THREAD

**Issue by herrernst** [kimono-koans/dano#10]
Hi, great project!
Can it be used to deduplicate media files that have the same content? E. g. one has a large mp3/aac collection, and there are some duplicates, but with different filenames/metadata/album art, and one likes to find them based on the checksum of stream content. Like an improved fdupes: https://github.com/adrianlopezroche/fdupes
Thanks

**Comment by kimono-koans** [comment]
> Hi, great project!
> Can it be used to deduplicate media files that have the same content? E. g. one has a large mp3/aac collection, and there are some duplicates, but with different filenames/metadata/album art, and one likes to find them based on the checksum of stream content. Like an improved fdupes: https://github.com/adrianlopezroche/fdupes
> Thanks

Yes, it would be possible to do this via `dano`, but AFAIK it can also be done via `bash`.  Would you create duplicate media files with different names and try to see if this is what you want: `find . -type f | dano -p * | sort -u -t: -k1,1 | uniq -f0 -D`?

Thanks!

**Comment by kimono-koans** [comment]
See: https://github.com/kimono-koans/dano/releases/tag/0.7.0

**Comment by herrernst** [comment]
Wow, that was fast! Thank you, it works!
