### ISSUE TITLE
"no valid paths to search" for opus (not in the extensions list)

### ISSUE THREAD

**Issue by rudluff** [kimono-koans/dano#11]
```
$ dano -w "モップス MOPS _傘がない Kasa Ga Nai  （1973年） [nDWv8UWt1us].opus"
Error: No valid paths to search.
$ dano -w "モップス MOPS _傘がない Kasa Ga Nai  （1973年） [nDWv8UWt1us].opus" --only=audio
Error: No valid paths to search.
$ dano -w "モップス MOPS _傘がない Kasa Ga Nai  （1973年） [nDWv8UWt1us].opus" --only=audio --decode
Error: No valid paths to search.
```
Two problems: 

1. Opus is a valid extension supported by ffmpeg that isn't in the extension list: https://github.com/kimono-koans/dano/blob/master/data/ffmpeg_extensions_list.txt
2. Error message bad, had me pulling my hair out for about 30 minutes trying to figure out if the command which initially caused this ( `find . -type f -exec dano -w -x --only=audio --canonical-paths {} \ ;` ) was somehow bugging out and where, before realizing that it works if you rename them ogg so it's just an extension list:
```
$ cp test.opus test.ogg
$ dano -w -x test.ogg
murmur3=942f168dbc9b76c338134332a9df7be5 : "test.ogg"
Writing dano hash for: "test.ogg"
$ setfattr  -x user.dano.checksum test.ogg 
$ dano -w -x test.ogg --only=audio
murmur3=f59fc5b901b9e64e7f3b6c7a4b98d440 : "test.ogg"
Writing dano hash for: "test.ogg"
```
Suggest adding opus to the list and also putting a more descriptive error message such as "Error: File type unknown or unsupported: <file basename>"

Thank you for making the dano!

**Comment by kimono-koans** [comment]
> Suggest adding opus to the list and also putting a more descriptive error message such as "Error: File type unknown or unsupported: "

Thank you for the very detailed bug report.  

Pleased to add `opus` to the list and include in the next minor release.  FYI, you can disable filtering with `--disable-filter` and I *think* `dano` will just keep trudging forward and only print an error when you use it.

As for the error, I can fix that too.

**Comment by kimono-koans** [comment]
See: https://github.com/kimono-koans/dano/commit/f8796fa59a182a0d2f1d97f7e3a95f07ce8f5e25

**Comment by rudluff** [comment]
Ooh, I missed that one in the help page. Thank you! I can do something like find . -iname "*.opus" to avoid ffmpeg rejection overload.

**Comment by kimono-koans** [comment]
Fixed in latest version.
