### ISSUE TITLE
Calculates hash differently from FLAC, resulting in --import-flac being broken

### ISSUE THREAD

**Issue by averms** [kimono-koans/dano#13]
## To reproduce

Download `Sample_BeeMoved_96kHz24bit.flac` from https://helpguide.sony.net/high-res/sample1/v1/en/index.html. I renamed it to `bee_moved.flac`. To reproduce:

```
• ~/.cargo/bin/dano --import-flac bee_moved.flac 
MD5=e5d100c63f5188900c66b6a6a08ce2eb : "bee_moved.flac"
Writing dano hash for: "bee_moved.flac"
• ~/.cargo/bin/dano -t bee_moved.flac 
WARN: "bee_moved.flac": Path has new hash for same filename.
• cat dano_hashes.txt 
// DANO, Invoked from: "/var/home/anon/Music/test"
{"version":4,"path":"bee_moved.flac","metadata":{"hash_algo":"MD5","hash_value":{"radix":16,"value":"e5d100c63f5188900c66b6a6a08ce2eb"},"last_written":{"secs_since_epoch":1713065051,"nanos_since_epoch":972071825},"modify_time":{"secs_since_epoch":1667455007,"nanos_since_epoch":0},"decoded":true,"selected_streams":"AudioOnly"}}
```

## Why

The ffmpeg cli's hash muxer implicitly converts audio to 16-bit signed PCM. `flac` avoids that, which is the correct approach.

**Comment by kimono-koans** [comment]
> The ffmpeg cli's hash muxer implicitly converts audio to 16-bit signed PCM. `flac` avoids that, which is the correct approach.

Good catch!  I'm surprised I had not noticed this before now.

It is possible to fix but `ffmpeg` doesn't make it easy.  `ffmpeg` requires one to specify the output format, and we can get the bit rate from `metaflac`:

```
% ffmpeg -i 'Sample.flac' -f s24le - | md5sum
...
52fcd6ad7b05dbcfe47ddaea6b9a0f7f  -
% metaflac --show-bps 'Sample.flac'
24
```

My only issue is this requires a new version and a new processing stage, and I have to decide how best to do that, but this is definitely fixable.

Thanks for the bug report!

**Comment by kimono-koans** [comment]
FYI, this branch fixes: https://github.com/kimono-koans/dano/tree/version_flac_bps

Right now, high bit rate FLAC must be imported via `--import-flac` to work.

Gonna sit with how this is implemented for awhile before releasing.

**Comment by averms** [comment]
> It is possible to fix but `ffmpeg` doesn't make it easy. `ffmpeg` requires one to specify the output format, and we can get the bit rate from `metaflac`:

You can also control the codec while still using the hash muxer. Like

```
% ffmpeg -i 'Sample.flac' -c pcm_s24le -f hash -hash md5 -
```
